### ISSUE TITLE
NetFlow V9 with VyOS.

### ISSUE THREAD

**Issue by benlavender** [logstash-plugins/logstash-codec-netflow#27]
Hello, got a small issue with NetFlow parsing with Logstash (1.4.5), where no data is showing in Kibana. I am successfully taking V9 flows from an IOS device. 
VyOS flow config:

```
interface eth0
netflow {
 engine-id 0
 sampling-rate 1
 server 192.168.10.3 {
     port 9995
 }
 timeout {
     expiry-interval 60
     flow-generic 180
     icmp 120
     max-active-life 300
     tcp-fin 360
     tcp-generic 360
     tcp-rst 60
     udp 120
  }
  version 9
 }
 syslog-facility daemon
```

My input takes syslog using the UDP plugin on UDP port 514 and my NetFlow takes it using the NetFlow codec using UDP port 9995 and sends to Elasticsearch depending on the type, which again works great on my test IOS router.

The errors I can find are from the logstash.log below:

{:timestamp=>"2015-10-21T15:10:34.857000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:10:46.605000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:11:01.598000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:11:14.606000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:11:28.653000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:11:40.647000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:12:06.652000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:12:19.647000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:12:31.632000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:12:49.607000+0100", :message=>"No matching template for flow id 256", :level=>:warn}
{:timestamp=>"2015-10-21T15:13:04.212000+0100", :message=>"No matching template for flow id 1024", :level=>:warn}

So my problem is something to do with the NetFlow.YAML file I’m using, is there another set I can use for this client only and I’ll single out the connection in the input/output.confs?

Thanks

**Comment by jorritfolmer** [comment]
It really depends on how often your Netflow exporter sends the template packets used to make sense of the Netflow data packets. The errors you get mean that Netflow v9 data packets were received without having first received a corresponding template to know which fields are actually included in the data packets. Packets containing templates are only sent once in a while, for example each minute. So usually these are transient error messages.

So there errors are not related to the netflow.yaml file, because to reach that stage it first has to apply the tempates to the data. It doensn't get that far.

Would you mind doing some packet capturing for - say 15 minutes - on your logstash instance so I can look at it? `tcpdump -i eth0 -s 0 -w /tmp/netflowv9_vyos.pcap udp and port 9995`. My email address is in my profile.

**Comment by benlavender** [comment]
Sure Jorrit I’ll get some of that over, I’ve seen the templates being sent periodically from an IOS device in the past but not captured any from this particular type of device. I’ll get that over.

**Comment by ehayon** [comment]
Were you ever able to resolve this? Trying to export VyOS netflow v9 to logstash but I'm getting "No matching template for flow id 1024"

**Comment by benlavender** [comment]
We didn’t implant it in the end, purely down to the change of requirements. This would be a similar issue to https://github.com/logstash-plugins/logstash-codec-netflow/issues/28 which I believe was resolved.

**Comment by jorritfolmer** [comment]
I'll leave this issue open as we don't have any confirmation that VyOS netflow actually works.
Please send me any .pcaps so I can add support and create the accompanying rspec tests.

**Comment by sliddjur** [comment]
@jorritfolmer I don't think am not able to capture the netflow v9 template package from vyos routers (release 1.1.7).
Are the template packages in clear text? All packages I see seem to be netflow encoded.

Logstash log outputs

```
[2016-12-06T11:29:23,692][WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>201, :length=>4}
[2016-12-06T11:31:41,512][WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>201, :length=>4}
[2016-12-06T11:31:41,512][WARN ][logstash.codecs.netflow  ] No matching template for flow id 1024
[2016-12-06T11:32:41,770][WARN ][logstash.codecs.netflow  ] No matching template for flow id 1024
```
Here is my logstash input config:

```
input {
        udp {
                port => 5044
                tags => ["netflow"]
                codec => netflow
                {
                        versions => [9]
                }
        }
}
```

Here is my vyos config

```
show system flow-accounting
 interface eth1.206
 interface eth0.42
 interface eth1.1805
 interface eth1.1806
 netflow {
     server 172.23.253.24 {
         port 5044
     }
     version 9
 }
 syslog-facility daemon
```

Attaching capture from netflow server to logstash server. Netflow capture. I've ran captures for 15 minutes, still not seeing any template packages.
[vyos-netflow.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/633578/vyos-netflow.zip)

**Comment by sliddjur** [comment]
More log:
```
[2016-12-06T13:36:47,031][WARN ][logstash.codecs.netflow  ] No matching template for flow id 256
[2016-12-06T13:36:51,031][WARN ][logstash.codecs.netflow  ] No matching template for flow id 256
[2016-12-06T13:51:39,535][WARN ][logstash.codecs.netflow  ] Template length doesn't fit cleanly into flowset {:template_id=>257, :template_length=>101, :record_length=>308}
[2016-12-06T13:52:42,887][WARN ][logstash.codecs.netflow  ] No matching template for flow id 1024
[2016-12-06T13:52:42,889][WARN ][logstash.codecs.netflow  ] No matching template for flow id 1024
[2016-12-06T13:52:42,892][WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>201, :length=>4}
[2016-12-06T13:56:43,145][WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>201, :length=>4}

```
I also added the netflow_definition field file in my input plugin.

cat netflow.yaml
```
---
256:
- :skip
1024:
- :skip

```

**Comment by jorritfolmer** [comment]
Thanks!. I've seen data templates in your .pcap, so that looks good.
I'll look further into it next weekend.

**Comment by sliddjur** [comment]
This is captured with tcpdump. It is sent by pmacctd. I am not managing to see a template packet here either @jorritfolmer. What is the procedure to actually decode the netflow data within wireshark?
[tcpdumc.wireshark.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/642096/tcpdumc.wireshark.zip)

**Comment by jorritfolmer** [comment]
1. Load pcap in Wireshark
2. Right-click somewhere in the flows
3. Select "Decode as" (second item from below)
4. Select "5044" from the 2nd dropdown, under value. This is the port you seem to be using for Netflow
5. Select "CFLOW" from the 3rd dropdown, under current. This is the protocol is will decode the flows as. Is probably says "(none)" now.

**Comment by jorritfolmer** [comment]
Good news! It seems that the current master branch supports the Vyos exported Netflow v9! From your pcap I can see it contains MPLS labels, for which I've pushed a new commit a week ago.
This is the debug output from one of your netflow packets:

```
{
       "netflow" => {
                    "output_snmp" => 0,
                        "in_pkts" => 7,
            "ip_protocol_version" => 4,
                  "ipv4_dst_addr" => "134.170.172.140",
                        "src_tos" => 0,
                 "first_switched" => "2016-12-06T09:28:56.999Z",
                     "in_dst_mac" => "00:50:56:bc:6a:27",
                     "flowset_id" => 1024,
                    "l4_src_port" => 2789,
                        "version" => 9,
                   "flow_seq_num" => 88671,
                  "ipv4_src_addr" => "172.23.253.10",
                     "in_src_mac" => "00:50:56:bc:11:f6",
                       "src_vlan" => 0,
                       "in_bytes" => 4514,
                       "protocol" => 6,
        "mpls_label_stack_octets" => {
            "bottom_of_stack" => 0,
               "experimental" => 0,
                      "label" => 0,
                        "ttl" => 8
        },
                  "last_switched" => "2016-12-06T09:28:57.999Z",
                     "input_snmp" => 8,
                          "flows" => 0,
                      "tcp_flags" => 219,
                    "l4_dst_port" => 443,
                      "direction" => 0
    },
    "@timestamp" => 2016-12-06T10:26:43.000Z,
      "@version" => "1",
          "host" => "172.16.32.201",
          "tags" => []
}
```

**Comment by jorritfolmer** [comment]
Is this still an issue?

**Comment by ashishbkadam** [comment]
Hi , i got similar issue for VyOS netflow version 9. Its working fine with version 5.
I am using latest version of logstash 5.2 and logstash-codec-netflow updated to latest 3.3 , still issue remains. VyOS version 1.1.7

I am getting following log in logstash

{:timestamp=>"2017-02-27T17:02:19.739000+0000", :message=>"Invalid netflow packet received (value '14' not as expected for obj.records[5].flowset_id)", :level=>:warn}
{:timestamp=>"2017-02-27T17:02:19.904000+0000", :message=>"No matching template for flow id 1024", :level=>:warn}
{:timestamp=>"2017-02-27T17:02:19.906000+0000", :message=>"No matching template for flow id 1024", :level=>:warn}
{:timestamp=>"2017-02-27T17:02:19.907000+0000", :message=>"No matching template for flow id 1024", :level=>:warn}
{:timestamp=>"2017-02-27T17:02:20.163000+0000", :message=>"No matching template for flow id 1024", :level=>:warn}
{:timestamp=>"2017-02-27T17:02:20.165000+0000", :message=>"No matching template for flow id 1024", :level=>:warn}

I have attached pcap and netflow.yaml file for more reference. Any help will be useful.

[netflow.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/809829/netflow.zip)

[netflow.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/809819/netflow.zip)

Thanks

**Comment by jorritfolmer** [comment]
Ah found it. The same symptoms appeared when implementing support for Cisco NBAR.
This has been fixed very recently. I've just pulled the nbar branch into master.

Can you try the current master branch?
If I replay your pcap (thanks btw!) it now decodes properly, e.g.:

```
{
       "netflow" => {
                    "output_snmp" => 0,
                        "in_pkts" => 1,
            "ip_protocol_version" => 4,
                  "ipv4_dst_addr" => "10.170.1.200",
                        "src_tos" => 0,
                 "first_switched" => "2017-02-27T18:55:16.999Z",
                     "in_dst_mac" => "00:00:5e:00:01:01",
                     "flowset_id" => 1024,
                    "l4_src_port" => 443,
                        "version" => 9,
                   "flow_seq_num" => 125466,
                  "ipv4_src_addr" => "10.255.1.183",
                     "in_src_mac" => "58:97:bd:98:0c:41",
                       "src_vlan" => 0,
                       "in_bytes" => 1353,
                       "protocol" => 6,
        "mpls_label_stack_octets" => {
            "bottom_of_stack" => 0,
               "experimental" => 0,
                      "label" => 0,
                        "ttl" => 9
        },
                  "last_switched" => "2017-02-27T18:55:16.999Z",
                     "input_snmp" => 9,
                          "flows" => 0,
                      "tcp_flags" => 24,
                "flow_sampler_id" => 1,
                    "l4_dst_port" => 38414,
                      "direction" => 0
    },
    "@timestamp" => 2017-02-27T18:57:00.000Z,
      "@version" => "1",
          "host" => "172.16.32.201",
          "tags" => []
}
```

**Comment by ashishbkadam** [comment]
@jorritfolmer ,Thanks it worked :)
