### ISSUE TITLE
No meaningful output for v9 data from Cisco ASR9K

### ISSUE THREAD

**Issue by analogbyte** [logstash-plugins/logstash-codec-netflow#57]
- Version: logstash 5.0.2-1 from RPM
- Operating System: CentOS 7.2.1511 with Kernel 3.10.0-327.36.3.el7.x86_64
- Config File:
```
input {
    udp {
        port => 9995
        codec => netflow
    }
}
output {
    elasticsearch { hosts => ["localhost:9200"] }
}
```
- Sample Data: I can not provide netflow data publicly due to data protection laws, but I can give you access to some in private.
- Steps to Reproduce: Run Logstash with above Config, get Netflow data from Cisco ASR9K.

As described by @niempy [here](https://github.com/elastic/logstash/issues/4165), only select fields make it to Elasticsearch, the rest is just missing. Also, data comes in only exactly once per minute in my case. The exact router version is:
```
#show version
Fri Dec  2 15:24:17.438 CET

Cisco IOS XR Software, Version 6.0.2[Default]
Copyright (c) 2016 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 10.50(c) 1994-2014 by Cisco Systems,  Inc.
router uptime is 2 weeks, 1 day, 22 hours, 7 minutes
System image file is "disk0:asr9k-os-mbi-6.0.2/0x100305/mbiasr9k-rsp3.vm"

cisco ASR9K Series (Intel 686 F6M14S4) processor with 16777216K bytes of memory.
Intel 686 F6M14S4 processor at 1904MHz, Revision 2.174
ASR-9010 8 Line Card Slot Chassis with V3 AC PEM

4 Management Ethernet
2 FastEthernet
32 TenGigE
32 DWDM controller(s)
32 WANPHY controller(s)
40 GigabitEthernet
```

The only fields appearing to be parsed correctly are:
```
#netflow.flow_sampler_id 1
#netflow.flow_sampler_mode 2
#netflow.flow_sampler_random_interval 1,000
#netflow.flow_seq_num 81,387,975
#netflow.flowset_id 257
tnetflow.sampler_name sm-xyz-vlan
tnetflow.scope_system 181969085
#netflow.version 9
t severity informational
t tags
t type netflow
```
and none other.

In addition, Logstash's logs look like the following excerpt, but I am not sure thats relevant:
```
[2016-12-02T14:51:10,068][WARN ][logstash.codecs.netflow  ] Invalid netflow packet received (value '0' not as expected for obj.records[0].flowset_id)
[2016-12-02T14:51:10,069][WARN ][logstash.codecs.netflow  ] No matching template for flow id 260
{... more of the id 260 lines here ...}
[2016-12-02T14:51:10,489][WARN ][logstash.codecs.netflow  ] No matching template for flow id 266
```

**Comment by jorritfolmer** [comment]
(Copy/paste from my answer in elastic/logstash#4165:)

I just finished replaying @jdambly's pcap file to my logstash-codec-netflow v3.1.2.
It looks good to me, with bytes_in etc, see below.

Perhaps the issue is only with sampled netflow output, instead of full netflow?
Could you both send me a .pcap privately with some of your netflow traffic @analogbyte @niempy?
I'll take a look at it, my email is in profile.

```
{
       "netflow" => {
            "output_snmp" => 1,
                 "dst_as" => 36180,
               "dst_mask" => 0,
                "in_pkts" => 1,
          "ipv4_dst_addr" => "10.1.1.14",
                "src_tos" => 0,
         "first_switched" => "2016-02-02T20:54:07.999Z",
             "flowset_id" => 256,
            "l4_src_port" => 161,
          "ipv4_next_hop" => "192.168.199.253",
               "src_mask" => 0,
                "version" => 9,
           "flow_seq_num" => 70603,
          "ipv4_src_addr" => "10.34.7.12",
               "in_bytes" => 105,
               "protocol" => 17,
          "last_switched" => "2016-02-02T20:54:07.999Z",
             "input_snmp" => 25,
              "tcp_flags" => 0,
        "flow_sampler_id" => 0,
            "l4_dst_port" => 33756,
              "direction" => 1,
                 "src_as" => 0
    },
    "@timestamp" => 2016-02-02T20:54:22.000Z,
      "@version" => "1",
          "host" => "172.16.32.201"
}
```

**Comment by analogbyte** [comment]
@jorritfolmer Done, thanks for looking into it 👍

**Comment by niempy** [comment]
@jorritfolmer   Done, many thanks for looking into it 👍

Below 2 screenshots from the pcap file (decoded with Wireshark latest version). 
Seems the router uses template 260. This is also in the capture. I guess decoding template 260 is the issue?

packet with actual netflow data
![payload](https://cloud.githubusercontent.com/assets/15903216/20962844/4b0f46f4-bc6b-11e6-8c24-4e00331eaf76.jpg)

package with netflow template:
![template_260](https://cloud.githubusercontent.com/assets/15903216/20962855/547f266e-bc6b-11e6-9ce1-4fb29038813e.jpg)

**Comment by jorritfolmer** [comment]
Can you try the patch below?

It now decodes forwarding_status (89) into these values according to http://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html

- status (2 bit value)
- reason (6 bit value)

On my dev vm this is the (anonymised) output I'm getting from one of your samples:

```
{
       "netflow" => {
              "output_snmp" => 210,
                   "dst_as" => 0,
                 "dst_mask" => 32,
        "forwarding_status" => {
            "reason" => 0,
            "status" => 1
        },
                  "in_pkts" => 1,
            "ipv4_dst_addr" => "10.0.0.114",
                  "src_tos" => 0,
           "first_switched" => "2016-12-07T07:22:55.999Z",
               "flowset_id" => 260,
              "l4_src_port" => 64673,
                 "src_mask" => 32,
                  "version" => 9,
             "flow_seq_num" => 185838573,
            "ipv4_src_addr" => "10.0.1.240",
                 "in_bytes" => 40,
                 "protocol" => 6,
               "input_snmp" => 215,
            "last_switched" => "2016-12-07T07:22:55.999Z",
                "tcp_flags" => 16,
          "flow_sampler_id" => 1,
        "bgp_ipv4_next_hop" => "0.0.0.0",
              "l4_dst_port" => 80,
                   "src_as" => 0,
                "direction" => 0
    },
    "@timestamp" => 2016-12-07T07:23:15.000Z,
      "@version" => "1",
          "host" => "172.16.32.201"
}
```

```patch
diff --git a/lib/logstash/codecs/netflow/netflow.yaml b/lib/logstash/codecs/netflow/netflow.yaml
index c288b6c..98e6a63 100644
--- a/lib/logstash/codecs/netflow/netflow.yaml
+++ b/lib/logstash/codecs/netflow/netflow.yaml
@@ -223,7 +223,7 @@
 - :uint32
 - :in_permanent_pkts
+89:
+- :forwarding_status
+- :forwarding_status
 95:
 - :uint32
diff --git a/lib/logstash/codecs/netflow/util.rb b/lib/logstash/codecs/netflow/util.rb
index 7b46930..6a0bbf0 100644
--- a/lib/logstash/codecs/netflow/util.rb
+++ b/lib/logstash/codecs/netflow/util.rb
@@ -72,6 +72,12 @@ class MPLSLabelStackOctets < BinData::Record
   uint8  :ttl
 end
 
+class Forwarding_Status < BinData::Record
+  endian :big
+  bit2   :status
+  bit6   :reason
+end
+
 class Header < BinData::Record
   endian :big
   uint16 :version
```

**Comment by analogbyte** [comment]
I can't get it to work and I think it's my fault. Do I need to compile this into class files somehow? I checked out the master branch, which refused your patch. I did the changes myself, and copied the whole thing into the subdir `/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.1.2/` of my installation. The exact diff I have is:

```diff
diff --git a/lib/logstash/codecs/netflow/netflow.yaml b/lib/logstash/codecs/netflow/netflow.yaml
index c288b6c..4fc73ba 100644
--- a/lib/logstash/codecs/netflow/netflow.yaml
+++ b/lib/logstash/codecs/netflow/netflow.yaml
@@ -222,12 +222,12 @@
 86:
 - :uint32
 - :in_permanent_pkts
-89:
-- :uint8
-- :forwarding_status
 95:
 - :uint32
 - :application_id
+89:
+- :uint8
+- :forwarding_status
 136:
 - :uint8
 - :flow_end_reason
diff --git a/lib/logstash/codecs/netflow/util.rb b/lib/logstash/codecs/netflow/util.rb
index 7b46930..6a0bbf0 100644
--- a/lib/logstash/codecs/netflow/util.rb
+++ b/lib/logstash/codecs/netflow/util.rb
@@ -72,6 +72,12 @@ class MPLSLabelStackOctets < BinData::Record
   uint8  :ttl
 end
 
+class Forwarding_Status < BinData::Record
+  endian :big
+  bit2   :status
+  bit6   :reason
+end
+
 class Header < BinData::Record
   endian :big
   uint16 :version
```
As you can see, I've moved the `89:` block to have it in the diff (only for this, not when running it), as it already was in the master branch. I also think yours has a little mistake, from my understanding the lines added in `netflow.yaml` under `89:` are supposed to be a type plus its name, in your diff the name is there twice.

So where did I go wrong? As it stands, logstash does exactly the same as before.

**Comment by niempy** [comment]
Hi Jorrit,
many thanks for the quick patch!
We run into an issue. We never compiled this stuff with gem. We need to do this cause we run on 3.1.2 and we want to run this patch with your latest version. We tried but failed. 

Is it possible you "compile" a version 3.1.5 so we can use that version? Or am I talking rubbish now.
Thanks. 

regards, mark

**Comment by niempy** [comment]
Hi, 
we got it upgraded to 3.14.

We did not have to change anything on the yaml file. The forwarding_status (89) was already okay in 3.1.4 

We added on line 75 of /u01/logstash/vendor/local_gems/64cba345/logstash-codec-netflow-3.1.4/lib/logstash/codecs/netflow/util.rb:

class Header < BinData::Record
  endian :big
  uint16 :version
end

Logstash restart and it worked! 

Thanks Jorrit for the support and your swift reactions.

**Comment by analogbyte** [comment]
I checked out 11baa9bf6366b16c8b8f399f3e6d4f8ec01f32b9 and tried to install by doing:
```bash
/usr/share/logstash/bin/logstash-plugin remove logstash-codec-netflow
/usr/share/logstash/bin/logstash-plugin generate --type codec --name netflow --path logstash-codec-netflow/
cd logstash-codec-netflow
/usr/share/logstash/bin/logstash-plugin install logstash-codec-netflow
```
But looking at the files placed by logstash-plugin in `/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.1.2/lib/logstash/codecs/netflow/util.rb` it is not the fixed version. Also the path is wrong, it says `3.1.2` although I've just installed `3.1.4`... Copying the files over the old version does not help either. I still think I'm missing something...

**Comment by jorritfolmer** [comment]
@analogbyte Are you sure there is not also a 3.1.4 directory as well as 3.1.2?
You'll have to wait a bit before I publish the "official" 3.1.4 gem outside of GitHub, I'm a bit short on time.

**Comment by analogbyte** [comment]
@jorritfolmer Yes I am. I have the correct version in that path now, installed via logstash-plugin (whatever difference it might make in comparison to putting the files there manually). It still is not working though.
I get the same output and logs as before, the logs have the following new warning though:

```
[2016-12-09T16:38:21,872][WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>234, :length=>4}
```

I haven't noticed that one before. I guess I'll wait for the newer gem, to rule out me doing stuff wrong :)

**Comment by jorritfolmer** [comment]
Ok I think that means you have 3.1.4 running. That's good!

However it seems your ASR9k sends (another) unsupported field. I've been using @niempy's pcap for testing that doesn't seem to contain them.

I'll look into it later. Can you point to the right Cisco ASR documentation regarding these netflow fields? I've found this, but not sure: 
http://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r5-2/cg-nat/configuration/guide/b_cgnat_cg52xasr9k/b_cgnat_cg52xasr9k_chapter_0100.html#concept_B9B1823F0617415E8E3014721FDC2BAC

**Comment by jorritfolmer** [comment]
I've pushed a small update to a new asr9k branch with some of the fields in the docs.
These seem to work with the .pcap you provided.

From reading the docs it seems that the ASR9k emits options templates that allow the decoder to resolve certain interface and vrf ids to names. In your pcap I've seen options templates that contain interface names like `TenGigE0_6_1_1`, but not for vrf names. I'm not yet sure why they're missing, or perhaps I haven't found them yet :)

**Comment by analogbyte** [comment]
I'm still seeing the same results as before, and I'm not entirely convinced I install it correctly. Could you comment on the following process I'm using:
```bash
# in /root
systemctl stop logstash
/usr/share/logstash/bin/logstash-plugin remove logstash-codec-netflow
git clone https://github.com/logstash-plugins/logstash-codec-netflow.git
cd logstash-codec-netflow
# in the repo
git checkout asr9k
cd ..
# back in /root
/usr/share/logstash/bin/logstash-plugin generate --type codec --name netflow --path logstash-codec-netflow/
cd logstash-codec-netflow
# in the repo
/usr/share/logstash/bin/logstash-plugin install logstash-codec-netflow # this is the subfolder generated, it doesn't look complete (the netflow.yaml is missing, for instance)
systemctl start logstash
```

The logs still look the same, too. And even though you bumped the version to `3.2.0` in that branch, It is still installed to `logstash-codec-netflow-3.1.2`, but I cannot say why that is.

**Comment by jorritfolmer** [comment]
Ok this is what I usually do:

1. systemctl stop logstash
1. edit `/usr/share/logstash/Gemfile`, find the line that contains the logstash-codec-netflow and specify the path you test with, so you can indeed freely do git checkout etc:

    ```
    gem "logstash-codec-netflow", :path => "/home/jfolmer/logstash-codec-netflow"
    ```

1. systemctl start logstash

**Comment by analogbyte** [comment]
Thanks for this simple method, `logstash-plugin` is very slow and apparently didn't work the way I thought it would. I managed to see the decoded data, thank you so much! I think all relevant info is being decoded, but maybe @9er (of our backbone department) can spot something that's missing?

If it is somehow useful for you, our logs show:
```
[WARN ][logstash.codecs.netflow  ] No matching template for flow id 260
[WARN ][logstash.codecs.netflow  ] No matching template for flow id 266
[WARN ][logstash.codecs.netflow  ] Template length doesn't fit cleanly into flowset {:template_id=>266, :template_length=>108,
[WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>236, :length=>32}
```
(stripped of timestamps and record sizes for filtering with `uniq`)

Again, thank you so much for your work and your quick response 👍

**Comment by 9er** [comment]
@jorritfolmer 
> From reading the docs it seems that the ASR9k emits options templates that allow the decoder to resolve certain interface and vrf ids to names. In your pcap I've seen options templates that contain interface names like TenGigE0_6_1_1, but not for vrf names. I'm not yet sure why they're missing, or perhaps I haven't found them yet :)

In the example provided, only the default VRF is used, so no other VRFs are configured. That's probably why there aren't any in the template. The ID is in that case 0x60000000, which is exactly what's appearing in our Kibana now :)

Thanks for the patch!

**Comment by jorritfolmer** [comment]
Thanks for the VRF clarification.
From your logs there are still some issues:

1. Another unsupported field, 236. I haven't been able to find any reference to field 236 in the ASR docs. I've been able to reproduce this from the pcap you provided, but I haven't located the actual flowset yet. I assume I can borrow the IPFIX definition of field 236 and apply it to Netflow v9?

2. Template length doesn't fit. This I've been able to reproduce with your previously provided pcap, and it seem to be an issue with the IPv6 flowsets (id 266). This is good news and I think it's a logical bug in the Netflow codec that needs fixing. It probably has to do with the way the codec calculates the expected size of the flow sets. It currently takes the size of the template packets (108 bytes) instead of the sum of the declared lengths in the templates (109 bytes). I'm surprised we didn't run into this much much earlier.

Thank you for your valuable feedback and pcaps.

**Comment by jorritfolmer** [comment]
I've pushed some commits to the asr9k branch to fix the issues above.
It appears the Cisco docs specify IPV6_FLOW_LABEL as 3 bytes, whereas the actual data templates emitted from an asr9k specify it as 4 bytes. This causes the template length doesn't fit errors.
For integer fields I've switched to using the specification In the templates instead of the Cisco specified ones.

This means with the most recent asr9k branch you'll also get proper decoding for ipv6 flows.

**Comment by jorritfolmer** [comment]
Is anyone using the asr9k branch? Should it be merged into the master branch?

**Comment by analogbyte** [comment]
@jorritfolmer We have been running from the asr9k branch in a semi-production environment with about 10 asr9k routers with no issues. I'd vote for a merge. Thank you again!

**Comment by niempy** [comment]
@jorritfolmer same here! I also vote for a merge. Thanks!

**Comment by jorritfolmer** [comment]
Merged
